exmo/exmo/urls.py
# -*- coding: utf-8 -*-
# This file is part of EXMO2010 software.
# Copyright 2010, 2011, 2013 Al Nikolov
# Copyright 2010, 2011 non-profit partnership Institute of Information Freedom Development
# Copyright 2012-2014 Foundation "Institute for Information Freedom Development"
# Copyright 2014-2016 IRSI LTD
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, patterns, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.generic import RedirectView

admin.autodiscover()


handler500 = 'exmo2010.views.views.server_error'


urlpatterns = patterns('',
    url(r'^license.txt$', RedirectView.as_view(url=settings.STATIC_URL + 'license.txt')),
    url(r'^release.txt$', RedirectView.as_view(url=settings.STATIC_URL + 'release.txt')),
)

urlpatterns += i18n_patterns('',
    url(r'^admin/settings/', include('livesettings.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^jsi18n/', 'django.views.i18n.javascript_catalog', {'packages': ['django.conf', 'django.contrib.admin']}),
    url(r'^ckeditor/upload/', 'exmo2010.views.views.ckeditor_upload', name='ckeditor_upload'),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^', include('exmo2010.urls', namespace='exmo2010', app_name='exmo2010')),
)


# Serve media files when DEBUG is True.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exmo/exmo2010/models/clarification.py
# -*- coding: utf-8 -*-
# This file is part of EXMO2010 software.
# Copyright 2010, 2011, 2013 Al Nikolov
# Copyright 2010, 2011 non-profit partnership Institute of Information Freedom Development
# Copyright 2012-2014 Foundation "Institute for Information Freedom Development"
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
import datetime

from ckeditor.fields import RichTextField
from django.db import models
from django.forms.models import modelform_factory
from django.utils.translation import ugettext_lazy as _

from core.utils import clean_message
from .base import BaseModel


class Clarification(BaseModel):
    """
    Модель уточнений, по наличию даты закрытия определяется
    закрыто уточнение или нет.
    """

    class Meta(BaseModel.Meta):
        permissions = (("view_clarification", "Can view clarification"),)

    score = models.ForeignKey("Score", verbose_name=_('score'))

    comment = RichTextField(blank=True, verbose_name=_('comment'), config_name='simplified')
    open_date = models.DateTimeField(auto_now_add=True, verbose_name=_('clarification open'))
    close_date = models.DateTimeField(null=True, blank=True, verbose_name=_('clarification close'))
    creator = models.ForeignKey("auth.User", verbose_name=_('creator'))

    answer = RichTextField(blank=True, verbose_name=_('comment'), config_name='simplified')

    close_user = models.ForeignKey("auth.User",
                                   null=True,
                                   blank=True,
                                   verbose_name=_('user who close'),
                                   related_name='clarification_close_user')

    def add_answer(self, user, answer):
        self.answer = clean_message(answer)
        self.close_user = user
        self.close_date = datetime.datetime.now()
        self.save()
        return self

    def answer_form(self, data=None):
        AnswerForm = modelform_factory(Clarification, fields=['answer'])
        return AnswerForm(data=data, prefix='answer_clarification_%s' % self.pk)

    @staticmethod
    def form(data=None):
        Form = modelform_factory(Clarification, fields=['comment'])
        return Form(data=data, prefix='clarification')

    def __unicode__(self):
        return _('clarification for {obj.score} from {obj.creator}').format(obj=self)

    @property
    def addressee(self):
        return self.score.task.user

exmo/claims/views.py
# -*- coding: utf-8 -*-
# This file is part of EXMO2010 software.
# Copyright 2010, 2011, 2013 Al Nikolov
# Copyright 2010, 2011 non-profit partnership Institute of Information Freedom Development
# Copyright 2012-2014 Foundation "Institute for Information Freedom Development"
# Copyright 2014-2015 IRSI LTD
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse

from .forms import ClaimReportForm
from core.response import JSONResponse
from core.utils import clean_message
from exmo2010.mail import mail_claim_deleted, mail_claim_new
from exmo2010.models import Claim, Monitoring, Score


@login_required
def claim_create(request, score_pk):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    score = get_object_or_404(Score, pk=score_pk)
    if not request.user.has_perm('exmo2010.add_claim', score):
        raise PermissionDenied

    form = Claim.form(request.POST)
    if form.is_valid():
        claim = score.add_claim(request.user, clean_message(form.cleaned_data['comment']))
        mail_claim_new(request, claim)

    redirect = reverse('exmo2010:score', args=[score.pk]) + '#claims'
    return HttpResponseRedirect(redirect)


@login_required
def claim_answer(request, claim_pk):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    claim = get_object_or_404(Claim, pk=claim_pk)
    if not request.user.has_perm('exmo2010.answer_claim', claim.score):
        raise PermissionDenied

    form = claim.answer_form(request.POST)
    if form.is_valid():
        claim.add_answer(request.user, clean_message(form.cleaned_data['answer']))
        mail_claim_new(request, claim)

    redirect = reverse('exmo2010:score', args=[claim.score.pk]) + '#claims'
    return HttpResponseRedirect(redirect)


@login_required
def claim_delete(request):
    """
    Удаление претензии (AJAX).

    """
    if request.is_ajax() and request.method == 'POST':
        claim_id = request.POST.get('pk')
        if claim_id is not None:
            claim = get_object_or_404(Claim, pk=claim_id)
            if not request.user.has_perm('exmo2010.delete_claim', claim.score):
                raise PermissionDenied
            claim.delete()
            mail_claim_deleted(request, claim)
            return JSONResponse(success=True)
    raise Http404


@login_required
def claim_report(request, monitoring_pk):
    """
    Отчёт по претензиям.

    """
    monitoring = get_object_or_404(Monitoring, pk=monitoring_pk)
    if not request.user.has_perm('exmo2010.admin_monitoring', monitoring):
        raise PermissionDenied

    all_claims = Claim.objects.filter(
        score__task__organization__monitoring=monitoring).order_by("open_date")

    if request.is_ajax():
        creator_id = request.REQUEST.get('creator_id')
        addressee_id = request.REQUEST.get('addressee_id')
        if creator_id is not None and addressee_id is not None:
            creator_id = int(creator_id)
            addressee_id = int(addressee_id)
            claims = all_claims.filter(close_date__isnull=False)
            if creator_id != 0:
                claims = claims.filter(creator__id=creator_id)
            if addressee_id != 0:
                claims = claims.filter(addressee__id=addressee_id)
            return TemplateResponse(request, 'manage_monitoring/_claim_report_table.html', {'claims': claims})
        else:
            raise Http404

    claims = all_claims.filter(close_date__isnull=True)

    addressee_id_list = all_claims.order_by().values_list(
        "addressee", flat=True).distinct()
    creator_id_list = all_claims.order_by().values_list(
        "creator", flat=True).distinct()

    if request.method == "POST":
        form = ClaimReportForm(
            request.POST,
            creator_id_list=creator_id_list,
            addressee_id_list=addressee_id_list
        )
        if form.is_valid():
            cd = form.cleaned_data
            creator_id = int(cd["creator"])
            addressee_id = int(cd["addressee"])
            if creator_id != 0:
                claims = claims.filter(creator__id=creator_id)
            if addressee_id != 0:
                claims = claims.filter(addressee__id=addressee_id)
    else:
        form = ClaimReportForm(
            creator_id_list=creator_id_list,
            addressee_id_list=addressee_id_list
        )

    return TemplateResponse(request, 'manage_monitoring/claim_report.html', {
        'monitoring': monitoring,
        'claims': claims,
        'form': form,
    })


@login_required
def claims_index(request):
    if not request.user.profile.is_expert:
        raise PermissionDenied

    if request.is_ajax():
        return TemplateResponse(request, 'home/_claims_index.html',
                                {'claims': request.user.profile.get_closed_claims()})
    else:
        return TemplateResponse(request, 'home/claims_index.html',
                            {'claims': request.user.profile.get_opened_claims()})

exmo/clarifications/views.py
# -*- coding: utf-8 -*-
# This file is part of EXMO2010 software.
# Copyright 2010, 2011, 2013 Al Nikolov
# Copyright 2010, 2011 non-profit partnership Institute of Information Freedom Development
# Copyright 2012-2014 Foundation "Institute for Information Freedom Development"
# Copyright 2014-2015 IRSI LTD
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.utils.translation import ugettext as _

from .forms import ClarificationReportForm
from core.utils import clean_message
from exmo2010.mail import mail_clarification
from exmo2010.models import Clarification, Monitoring, Score


@login_required
def clarification_create(request, score_pk):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    score = get_object_or_404(Score, pk=score_pk)
    if not request.user.has_perm('exmo2010.add_clarification', score):
        raise PermissionDenied

    form = Clarification.form(request.POST)
    if form.is_valid():
        clarification = score.add_clarification(request.user, clean_message(form.cleaned_data['comment']))
        mail_clarification(request, clarification)

    redirect = reverse('exmo2010:score', args=[score.pk]) + '#clarifications'
    return HttpResponseRedirect(redirect)


@login_required
def clarification_answer(request, clarification_pk):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    clarification = get_object_or_404(Clarification, pk=clarification_pk)
    if not request.user.has_perm('exmo2010.answer_clarification', clarification.score):
        raise PermissionDenied

    form = clarification.answer_form(request.POST)
    if form.is_valid():
        clarification.add_answer(request.user, clean_message(form.cleaned_data['answer']))
        mail_clarification(request, clarification)

    redirect = reverse('exmo2010:score', args=[clarification.score.pk]) + '#clarifications'
    return HttpResponseRedirect(redirect)


@login_required
def clarification_report(request, monitoring_pk):
    """
    Отчёт по уточнениям.

    """
    monitoring = get_object_or_404(Monitoring, pk=monitoring_pk)
    if not request.user.has_perm('exmo2010.admin_monitoring', monitoring):
        raise PermissionDenied

    all_clarifications = Clarification.objects.filter(
        score__task__organization__monitoring=monitoring).order_by("open_date")
    title = _('Clarifications report for "%s"') % monitoring.name

    if request.is_ajax():
        creator_id = request.REQUEST.get('creator_id')
        addressee_id = request.REQUEST.get('addressee_id')
        if creator_id is not None and addressee_id is not None:
            creator_id = int(creator_id)
            addressee_id = int(addressee_id)
            clarifications = all_clarifications.filter(close_date__isnull=False)
            if creator_id != 0:
                clarifications = clarifications.filter(creator__id=creator_id)
            if addressee_id != 0:
                clarifications = clarifications.filter(score__task__user__id=addressee_id)
            return TemplateResponse(request, 'manage_monitoring/_clarification_report_table.html', {
                'clarifications': clarifications
            })
        else:
            raise Http404

    clarifications = all_clarifications.filter(close_date__isnull=True)

    addressee_id_list = all_clarifications.order_by().values_list(
        'score__task__user', flat=True).distinct()
    creator_id_list = all_clarifications.order_by().values_list(
        "creator", flat=True).distinct()

    if request.method == "POST":
        form = ClarificationReportForm(
            request.POST,
            creator_id_list=creator_id_list,
            addressee_id_list=addressee_id_list
        )
        if form.is_valid():
            cd = form.cleaned_data
            creator_id = int(cd["creator"])
            addressee_id = int(cd["addressee"])
            if creator_id != 0:
                clarifications = clarifications.filter(
                    creator__id=creator_id)
            if addressee_id != 0:
                clarifications = clarifications.filter(
                    score__task__user__id=addressee_id)
    else:
        form = ClarificationReportForm(
            creator_id_list=creator_id_list,
            addressee_id_list=addressee_id_list
        )

    return TemplateResponse(request, 'manage_monitoring/clarification_report.html', {
        'monitoring': monitoring,
        'title': title,
        'clarifications': clarifications,
        'form': form,
    })


@login_required
def clarifications_index(request):
    if not request.user.profile.is_expert:
        raise PermissionDenied

    if request.is_ajax():
        return TemplateResponse(request, 'home/_clarifications_index.html',
                                {'clarifications': request.user.profile.get_closed_clarifications()})
    else:
        return TemplateResponse(request, 'home/clarifications_index.html',
                                {'clarifications': request.user.profile.get_opened_clarifications()})

exmo/templates/scores/_claim.html
{% comment %}
# This file is part of EXMO2010 software.
# Copyright 2010, 2011, 2013 Al Nikolov
# Copyright 2010, 2011 non-profit partnership Institute of Information Freedom Development
# Copyright 2012-2014 Foundation "Institute for Information Freedom Development"
# Copyright 2014-2015 IRSI LTD
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
{% endcomment %}
{% load i18n %}
{% load bleach from bleach_tags %}
{% load linkify from exmo2010_filters %}

{% if score.perms.view_claim %}
    {% if claim_list %}
    <table class="table-messages-parameter">
        <tbody>
        {% for c in claim_list %}
            <tr>
                <td {% if not c.close_user and not score.perms.add_claim %} class="not-answered"{% endif %}>
                    <span class="messages-author"> {{ c.creator.profile.legal_name }} </span>

                    <span class="messages-date"> {{ c.open_date|date:"DATETIME_FORMAT" }} </span>

                    <div class="messages-content"> {{ c.comment|linkify|bleach }} </div>

                    {% if score.perms.delete_claim %}
                    <div class="claim-delete-container">
                        <a class="delete-claim pseudo" href="{% url 'exmo2010:claim_delete' %}" rel="{{ c.pk }}"> {% trans "Delete claim" %} </a>
                    </div>
                    {% endif %}

                    {% if c.answer %}
                    <div class="messages-answer">
                        <span class="messages-author"> {{ c.close_user.profile.legal_name }} </span>
                        <span class="messages-date"> {{ c.close_date|date:"DATETIME_FORMAT" }} </span>
                        <div class="messages-content"> {{ c.answer|linkify|bleach }} </div>
                    </div>
                    {% endif %}

                    {% if not request.user.is_superuser and c.creator != request.user and not c.answer and score.perms.answer_claim %}
                        <div class="messages-reply">
                            <a class="answer_form_toggle pseudo" href="#" data-prefix="{{ c.answer_form.prefix }}">
                                {% trans "Answer claim" %}
                            </a>
                        </div>

                        <div class="answer_form reply-form-tweak" style="display: none;">
                            <form action="{% url 'exmo2010:claim_answer' c.pk %}" method="post">{% csrf_token %}
                                <div class="fieldWrapper">
                                    <h3 class="claim-label heading-yourmessage-parameter">{% trans "Your claim answer" %}</h3>
                                    {{ c.answer_form.answer }}
                                    <input type="submit" disabled="disabled" class="submit-post" value="{% trans 'Reply' %}">
                                </div>
                            </form>
                        </div>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        {% trans 'There are no claims' %}
    {% endif %}
{% endif %}

{% if score.perms.add_claim %}
    <div id="add-claim">
        <form action="{% url 'exmo2010:claim_create' score.pk %}" method="post">{% csrf_token %}
            <div class="fieldWrapper">
                <h3 class="claim-label heading-yourmessage-parameter">{% trans "Your claim" %}</h3>
                {{ exmo2010.models.Claim.form.comment }}
                <input type="submit" disabled="disabled" class="submit-post" value="{% trans 'Put forward' %}">
            </div>
        </form>
    </div>
{% endif %}

exmo/templates/scores/_clarification.html
{% comment %}
# This file is part of EXMO2010 software.
# Copyright 2010, 2011, 2013 Al Nikolov
# Copyright 2010, 2011 non-profit partnership Institute of Information Freedom Development
# Copyright 2012-2014 Foundation "Institute for Information Freedom Development"
# Copyright 2014-2015 IRSI LTD
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
{% endcomment %}
{% load i18n %}
{% load bleach from bleach_tags %}
{% load linkify from exmo2010_filters %}

{% if score.perms.view_clarification %}
    {% if score.clarification_set.all %}
        <table class="table-messages-parameter">
            <tbody>
            {% for c in score.clarification_set.all %}
                <tr>
                    <td {% if not c.close_user and not score.perms.add_clarification %} class="not-answered"{% endif %}>
                        <span class="messages-author"> {{ c.creator.profile.legal_name }} </span>

                        <span class="messages-date"> {{ c.open_date|date:"DATETIME_FORMAT" }} </span>

                        <div class="messages-content"> {{ c.comment|linkify|bleach }} </div>

                        {% if c.answer %}
                            <div class="messages-answer">
                                <span class="messages-author"> {{ c.close_user.profile.legal_name }} </span>
                                <span class="messages-date"> {{ c.close_date|date:"DATETIME_FORMAT" }} </span>
                                <div class="messages-content"> {{ c.answer|linkify|bleach }} </div>
                            </div>
                        {% endif %}

                        {% if not request.user.is_superuser and c.creator != request.user and not c.answer and score.perms.answer_clarification %}
                            <div class="messages-reply">
                                <a class="answer_form_toggle pseudo" href="#" data-prefix="{{ c.answer_form.prefix }}">
                                    {% trans "Answer clarification" %}
                                </a>
                            </div>

                            <div class="answer_form reply-form-tweak" style="display: none;">
                                <form action="{% url 'exmo2010:clarification_answer' c.pk %}" method="post">{% csrf_token %}
                                    <div class="fieldWrapper">
                                        <h3 class="claim-label heading-yourmessage-parameter">{% trans "Your clarification answer" %}</h3>
                                        {{ c.answer_form.answer }}
                                        <input type="submit" disabled="disabled" class="submit-post" value="{% trans 'Reply' %}">
                                    </div>
                                </form>
                            </div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        {% trans 'There are no clarifications' %}
    {% endif %}
{% endif %}

{% if score.perms.add_clarification %}
    <div id="add-clarification">
        <form action="{% url 'exmo2010:clarification_create' score.pk %}" method="post">{% csrf_token %}
            <div class="fieldWrapper">
                <h3 class="clarification-label heading-yourmessage-parameter">{% trans "Your clarification" %}</h3>
                {{ exmo2010.models.Clarification.form.comment }}
                <input type="submit" disabled="disabled" class="submit-post" value="{% trans 'Clarify' %}">
            </div>
        </form>
    </div>
{% endif %}

exmo/templates/scores/_recomm_comments.html
{% comment %}
# This file is part of EXMO2010 software.
# Copyright 2014 Foundation "Institute for Information Freedom Development"
# Copyright 2014-2015 IRSI LTD
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
{% endcomment %}
{% load i18n comments %}
{% load bleach from bleach_tags %}
{% load set_data from widget_tweaks %}
{% load date_until linkify remove_extra_dot from exmo2010_filters %}

{% for comment in score.comments %}
    {% if forloop.first %}
        {% if score.comments|length > 2 or score.is_finished or not score.is_relevant %}
            <div class="comment-toggle show">
                {% blocktrans count counter=score.comments|length %} Show all {{ counter }} comments {% plural %} Show all {{ counter }} comments {% endblocktrans %}
            </div>
            <div class="comment-toggle hide hidden">
                {% trans 'Hide comments' %}
            </div>
        {% else %}
            <hr>
        {% endif %}
    {% endif %}
    <div class="comment" id="comment_{{ comment.pk }}">
        <span class="author">
            {% if comment.posted_by_expert and not request.user.is_expert %}
                {{ masked_expert_name }}
            {% else %}
                {{ comment.user.legal_name }}
            {% endif %}
        </span>
        <span class="date"> {{ comment.submit_date|date:"DATETIME_FORMAT" }} </span>
        <div class="body"> {{ comment.comment|linkify|bleach }} </div>
        {% if request.user.is_organization and not comment.posted_by_expert and comment.status == comment.OPEN %}
            <div class="comment_deadline">
                {% blocktrans with deadline_date=comment.submit_date|date_until:score.parameter.monitoring.time_to_answer|date:"DATE_FORMAT"|remove_extra_dot %}Deadline for answer to your comment is {{ deadline_date }}.{% endblocktrans %}
            </div>
        {% endif %}
    </div>
{% endfor %}

{% if request.user.is_organization %}
    {% if score.parameter.monitoring.is_interact %}
        <div class="comment-form {% if score.is_finished or not score.is_relevant %} hidden {% endif %}">

            <input type="text" class='fake_input' placeholder="{% trans 'Comment' context 'verb' %}" />

            <div class="hidden">
                <form method="post" action="{% url 'exmo2010:post_score_comment' score.pk %}">{% csrf_token %}
                    <input type="hidden" name="next" value="{% url 'exmo2010:recommendations' view.task.pk %}#param{{ score.parameter.pk }}" />

                    {% comment %}
                        # BUG 2377: We have to initialize ckeditor only on demand - after user clicks on fake_input. Set
                        # data-processed=1 to prevent automatic initialization in ckeditor-init.js
                    {% endcomment %}
                    {{ score.comment_form.comment|set_data:"processed:1" }}

                    <input type="submit"  class="tab-reply-block" value="{% trans 'Post comment' %}" disabled="disabled" />
                </form>
            </div>
        </div>
    {% elif score.parameter.monitoring.is_finishing %}
        <div class="comment_forbidden_notice">
            {% trans "You can't leave new comments. We will answer last comments and adjust scores." %}
        </div>
    {% elif score.parameter.monitoring.is_published %}
        <div class="comment_forbidden_notice">
            {% trans "Rating is published. You can't leave new comments." %}
        </div>
    {% endif %}
{% endif %}